### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by botezat** [Sorrow446/HRA-DL-highresaudio.com#4]
Hi **Sorrow446** :)

https://www.highresaudio.com/en/album/view/sw38qz/shirley-horn-softly-remastered

and please add to download cover + booklet

Thanks :)

**Comment by Sorrow446** [comment]
All tracks come already tagged with covers from the API. There's code to download booklets, but I need to fix it.

**Comment by botezat** [comment]
https://www.highresaudio.com/en/album/view/re6m2p/charles-lloyd-charles-lloyd-manhattan-stories-remastered
![1](https://user-images.githubusercontent.com/50467655/62840186-f99a3b80-bc9e-11e9-939c-f4ee871af1b1.jpg)

**Comment by Sorrow446** [comment]
Got a good idea of what's causing this. My fault. Will fix tonight if I get the time.

**Comment by botezat** [comment]
**Sorrow446** Thank you very much :)

**Comment by Sorrow446** [comment]
Fixed in r1a - Sorry for the trouble. Enjoy.

**Comment by botezat** [comment]
Very good :)
A million thanks to you, **Sorrow446**!
