### ISSUE TITLE
problem download again

### ISSUE THREAD

**Issue by botezat** [Sorrow446/HRA-DL-highresaudio.com#5]
https://www.highresaudio.com/en/album/view/tfm62q/quality-control-quality-control-control-the-streets-volume-2
![1](https://user-images.githubusercontent.com/50467655/63159171-86d4eb80-c023-11e9-8fdb-6333e59d1180.jpg)

**Comment by Sorrow446** [comment]
Will look into tomorrow. Thank you.

**Comment by Sorrow446** [comment]
Yeah, they straight up didn't return a URL. Check this album on their streaming app. It's probably restricted from streaming.

**Comment by botezat** [comment]
in the player is playing
![1](https://user-images.githubusercontent.com/50467655/63216607-60f13900-c140-11e9-8d90-b1619cbedb4d.jpg)

please look at the numbering of tracks

p.s. this album: https://www.highresaudio.com/en/album/view/pdku6v/jackson-browne-running-on-empty-remastered

**Comment by botezat** [comment]
sorry, this is a service error anyway.

Thanks!
